# Generated by Django 3.1.1 on 2020-09-10 23:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedores',
            fields=[
                ('CodigoFornecedor', models.AutoField(primary_key=True, serialize=False)),
                ('NomeFornecedor', models.CharField(max_length=100)),
                ('EmailFornecedor', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
